### ISSUE TITLE
Needs "stop_before" argument

### ISSUE THREAD

**Issue by ericearl** [DCAN-Labs/abcd-dicom2bids#13]
There's a `--start_at` option, but there's no `--stop-before` argument.  This would be very useful for people who just want to use this toold for downloading data, for instance.

**Comment by GregConan** [comment]
Addressed in [May 19 commit](https://github.com/DCAN-Labs/abcd-dicom2bids/commit/f7233d97ad8a278b09d5cec340ecf0ed97faacf0)
