### ISSUE TITLE
Subject List Argument

### ISSUE THREAD

**Issue by tientong98** [DCAN-Labs/abcd-dicom2bids#14]
I run into issues with a couple of things from this argument, the first thing is I got this error:

> NameError: name 'validate_readable_file' is not defined

which is the error from this:

https://github.com/DCAN-Labs/abcd-dicom2bids/blob/112b07308fa40b98f2450cf2bdece342b88ec3f2/abcd2bids.py#L205-L206

Should it be `type=valid_readable_file` instead? Also, if this argument is only optional, should `required=False`?

Lastly, should all `args ` in this portion be `cli_args`?

https://github.com/DCAN-Labs/abcd-dicom2bids/blob/112b07308fa40b98f2450cf2bdece342b88ec3f2/abcd2bids.py#L620-L696

**Comment by ericearl** [comment]
@GregConan Didn't you fix this?  Can you please merge those changes into master and do a new release?

**Comment by GregConan** [comment]
Fixed in `feature/issue-11-and-13` branch. Just merged to master with a [new release](https://github.com/DCAN-Labs/abcd-dicom2bids/releases/tag/2.2.0).
