### ISSUE TITLE
Undocumented dependency on jq

### ISSUE THREAD

**Issue by carlosivanr** [DCAN-Labs/abcd-dicom2bids#17]
I'm sure users will eventually figure it out, but the dependency on jq is missing from the Readme list.  I was also wondering if there's a way to specify which functional files to download (MID, SST, nBack, vs rest)?

**Comment by ericearl** [comment]
@GregConan Can you please update the README about the jq requirement?

@carlosivanr Great catch!  Sorry we missed it in the README.  To limit what the scripts choose to download, you can modify the abcd_fastqc01 spreadsheet to onloy contain series you want to select.  So to do what you're proposing you would just remove any rows having to do with images besides the MID, SST, nback, or rest fMRI scans.

**Comment by carlosivanr** [comment]
Great! Thank you for the advice. I'll try that out here soon.
Best,
C

**Comment by GregConan** [comment]
Fixed in [commit on 2020-07-21](https://github.com/DCAN-Labs/abcd-dicom2bids/commit/412eb19fa368ac7bebb5786ddbaa7ece897003a4)
