### ISSUE TITLE
MID sequences won't download

### ISSUE THREAD

**Issue by hasgrig** [DCAN-Labs/abcd-dicom2bids#20]
I have tried downloading multiple MID sequences through the tool but they will not download despite setting ftq_usable flag to 1. I was able to download the datasets using aws s3 cp but not through abcd-dicom2bids. Other sequences get downloaded fast.

**Comment by perronea** [comment]
My apologies for the delay in response. Is this still an issue you are having? I've been unable to replicate this on my end. Can you send me the command you were using?

**Comment by perronea** [comment]
I'm closing this issue for lack of communication.
