### ISSUE TITLE
No effective echo spacing for Philips task-fmri scans

### ISSUE THREAD

**Issue by carlosivanr** [DCAN-Labs/abcd-dicom2bids#21]
Hi there,

When running the abcd2bids.py tool, I've noticed that the correct_jsons step will output "No EffectiveEchoSpacing" for the task-fmri runs collected from Philips scanners (both Ingenia and Achieva). The corresponding .json files for task fmri will not have the echo spacing nor total read out time fields. The fieldmap .json files, on the other hand, will have the effective echo spacing and total read out time fields. I'm curious if this behavior is intentional?

**Comment by ericearl** [comment]
@carlosivanr Great question.  That is the intention.  The fmap JSON files need that information for our pipeline, but the func JSON files do not.  Also, [the BIDS standard here](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#in-plane-spatial-encoding) says the field is recommended (not required), so we opted not to inject it into the task JSONs since we didn't need to.

**Comment by carlosivanr** [comment]
Thanks @ericearl . I was curious because I noticed scans from other non-Philips scanners do have effective echo spacing in the .json sidecars. I did see that when on the correct_jsons step of the abcd2bids.py wrapper, the script will print out that the task-fmri runs from Philips scanners only do not have the effective echo spacing and then this causes another warning when trying to run fmriprep as it will prevent it from performing field map correction.

**Comment by ericearl** [comment]
Oh!  I see.  Well then, I'm going to re-open this issue and talk it over with our team for the appropriate solution.

**Comment by perronea** [comment]
I've been unable to replicate this issue. There are some subjects that do not have EffectiveEchoSpacing or DwellTime, but for these subjects those fields are injected into the sidecar json (see: https://github.com/DCAN-Labs/abcd-dicom2bids/blob/master/src/sefm_eval_and_json_editor.py#L415). It's possible that if you are using an outdated version pybids then it will not recognize the functional images in your BIDS dataset. Make sure you are using the pybids version that is specified in src/requirements.txt. As of now that is pybids==0.12.4

If you continue to get this error then please send me a subject list along with stdout/stderr to perr0372@umn.edu
