### ISSUE TITLE
download_nda_data and unpack_and_setup steps support different subject list standards

### ISSUE THREAD

**Issue by ericearl** [DCAN-Labs/abcd-dicom2bids#26]
The `download_nda_data` step takes either `NDAR_INV`, `NDARINV`, or `sub-NDARINV` as a subject prefix in the subject list file because the method using the subject list file can take any of those, but the `unpack_and_setup` step only uses a `sub-NDARINV` prefix correctly.  I think either both steps should take any of those or the README needs to be more explicit around the subject list.

**Comment by perronea** [comment]
@perronea edit this portion of the code to identify the pguid for each subject and feed the bids formatted subject id into unpack_and_setup.sh

https://github.com/DCAN-Labs/abcd-dicom2bids/blob/master/abcd2bids.py#L645

**Comment by perronea** [comment]
resolved with https://github.com/DCAN-Labs/abcd-dicom2bids/commit/0b9495fe80b078548f3911435d050c7ade2b2349
