### ISSUE TITLE
Dockerize the repository

### ISSUE THREAD

**Issue by GregConan** [DCAN-Labs/abcd-dicom2bids#27]
Put the code into a Docker container so users don't have to get all the right versions of all the dependencies

**Comment by GregConan** [comment]
[This issue is now being tracked on the ABCD-STUDY fork of this repository](https://github.com/ABCD-STUDY/abcd-dicom2bids/issues)

**Comment by audreymhoughton** [comment]
Closing this due to codebase transition plans.
