### ISSUE TITLE
Import Python scripts instead of running them via the terminal

### ISSUE THREAD

**Issue by GregConan** [DCAN-Labs/abcd-dicom2bids#28]
Import these Python scripts as packages instead of running them indirectly with `subprocess`:

- `aws_downloader.py`
- `correct_jsons.py`
- `nda_aws_token_maker.py`

Keeping everything within Python as much as possible makes it easier to debug and work with

(suggested by @paul-reiners)

**Comment by audreymhoughton** [comment]
Closing this due to codebase transition plans. (I do think some of this was done already, though)
