### ISSUE TITLE
Refactor unpack_and_setup.sh in Python

### ISSUE THREAD

**Issue by GregConan** [DCAN-Labs/abcd-dicom2bids#29]
...or at least the parts that call other Python scripts, namely

- run_order_fix.py
- sefm_eval_and_json_editor.py

Keeping everything within Python as much as possible makes it easier to debug and work with

(suggested by @paul-reiners)

**Comment by ericfeczko** [comment]
Let's include the other matlab scripts as well:

- run_data_gatherer.sh
-eta_squared.sh 

Neither of these really need to be in matlab -- and the MCRcache is a huge problem with the code as is when downloading >1,000 participants from the NDA>

**Comment by ericfeczko** [comment]
Based on our discussion today in computing team -- we should make this a bigger priority.

**Comment by audreymhoughton** [comment]
Closing this due to codebase transition plans.
