### ISSUE TITLE
Replace homebrewed functions with already-existing Python libraries

### ISSUE THREAD

**Issue by GregConan** [DCAN-Labs/abcd-dicom2bids#30]
- Replace get_and_print_timestamp_when with a Python logging library. We shouldn't have to make a custom function for this because "it's the 21st century!" (-@paul-reiners) and [Python already has a built in logging library](https://docs.python.org/3/library/logging.html)
- Replace default TEMP_FILES_DIR with functionality from [Python tempfile library](https://docs.python.org/3/library/tempfile.html). This should make the `cleanup` and `set_to_cleanup_and_crash` functions unnecessary because the library should automatically delete temporary files/folders

**Comment by audreymhoughton** [comment]
Closing this due to codebase transition plans.
