### ISSUE TITLE
Add more logging

### ISSUE THREAD

**Issue by GregConan** [DCAN-Labs/abcd-dicom2bids#38]
- Add a --verbose flag to print each command before running it if the flag is included
- Alternatively, add a flag so that the code _only_ prints each command _instead_ of running it?

**Comment by GregConan** [comment]
Maybe add a `--run` flag with 3 options:

1. `dry-run` to print every command without actually running it
2. `debug` to print every command before running it
3. `normal` (default) to run every command without printing

Or add a `--run` flag that takes `run`, `print`, or both words as parameters to indicate which the script should do?

**Comment by audreymhoughton** [comment]
Closing this due to codebase transition plans.
