### ISSUE TITLE
example DAL_ABCD_merged_pcqcinfo.csv?

### ISSUE THREAD

**Issue by DVSneuro** [DCAN-Labs/abcd-dicom2bids#4]
Hi -- I see that the actual `DAL_ABCD_merged_pcqcinfo.csv` file is only available through your lab, but could you post an example of what it would look like? Does it require specific header names? If so, what are they? What are the expected/allowable values in the columns? 

Sorry if I'm missing something!

Best,
David

**Comment by ericearl** [comment]
@DVSneuro Good news, we are nearly complete with a new release that will rely on the abcd_fastqc01 instrument from the NDA directly.  This will eliminate the need for the `DAL_ABCD_merged_pcqcinfo.csv`.  Click the "Watch" button above on this repository to see it when we make that release.  It will be before NOV 15.

**Comment by DVSneuro** [comment]
Sounds great, thanks! We'll be on the lookout for that.

**Comment by ericearl** [comment]
@DVSneuro It has been released as v2.0.0 here.  This should make the need for the `DAL_ABCD_merged_pcqcinfo.csv` irrelevant.

https://github.com/ABCD-STUDY/abcd-dicom2bids/releases/tag/v2.0.0
