### ISSUE TITLE
Data with "Replaced" rows in abcd_fastqc01 no longer works as expected

### ISSUE THREAD

**Issue by ericearl** [DCAN-Labs/abcd-dicom2bids#40]
Hey folks!  Until the NDA deletes the rows that say "Replaced" in them in the `abcd_fastqc01` file, the abcd-dicom2bids repo has the danger of downloading a file which has been replaced instead of its replacement.

What happens is there are two rows sometimes for one TGZ file, one of which says `"Replaced"` in the `abcd_fastqc01` and one that does not.  abcd-dicom2bids lines up all the files and downloads the ones with `ftq_usable` of `1`.  Instead of ignoring the `"Replaced"` row, it just downloads whichever one it "sees" first, I think,  The next row where it sees that same TGZ basename, it is flagged as "this file already exists" and a little message to that effect goes to stdout.

Anyway, hopefully there's a good programmatic solution to mitigate this error that **may or may not** actually cause a problem in what files are downloaded.  Thanks!

**Comment by hough129** [comment]
Hi @ericearl - @perronea and I tested to see if this caused a problem, and we couldn't replicate seeing two rows for the same TGZ file. I believe @perronea looked up the exact TGZ filename you were seeing duplicates for that you sent in your email, and that duplicate did not exist in the most recent version of the abcd_fastqc01 at the time.

**Comment by ericearl** [comment]
@hough129 I just re-downloaded the abcd_fastqc01 yesterday and it had rows with "Replaced" in them?  How are you not seeing those?  Especially for baseline data?

**Comment by hough129** [comment]
I will defer to @perronea to see if he's managed to replicate it since the time we met about it.

**Comment by ericfeczko** [comment]
@ericearl which abcd_fastqc01 file are you downloading? I recall another thread where it turned out we were not downloading the same file, may that be the case here?

**Comment by ericearl** [comment]
@ericfeczko Details from my NDA abcd_fastqc01 download's "dataset_collection.txt" file below.

| "submission_id" | "dataset_id" | "collection_id" | "collection_title" | "pi_list" |
| --- | --- | --- | --- | --- |
| "45264" | "47631" | "2573" | "Adolescent Brain Cognitive Development Study (ABCD)" | "Terry L. Jernigan" |

**Comment by ericfeczko** [comment]
Thanks! 
We're a little slammed now with other priorities, and neither ours nor Don's group have seen this issue. 
If we encounter this problem within our own abcd_fastqc01 we'll definitely clarify and let you know. if you've heard of other groups having this issue, feel free to have them reach out as well. 

Hopefully we'll have time to tackle the coding issue after New Year's.

**Comment by perronea** [comment]
@ericearl I just download the latest fastqc and it has almost double the number of entries along with some duplicates (the same tgz with multiple passing qc flags). I'm not sure what changed between this download and the download from a month ago when this wasn't an issue... Can you confirm if a single tgz has both a `Replaced` and a `ftq_usable` of `1`. I suspect that the `Replaced` tgzs no longer pass qc and the duplicates are simply from multiple uploads that are in fact the same image. If this is the case then it doesn't matter which tgz our code downloads so the performance won't be affected.

**Comment by ericfeczko** [comment]
Thanks @perronea ! I suspect that the fast track qc might have been updated over the past week. 

@ericearl can you report this to the NDA help desk as a ticket issue? Feel free to tag us in the help desk email.

**Comment by perronea** [comment]
@ericfeczko Removing the redundancies would be nice, but as long as there is no conflicts (different tgzs that are named the same both with `ftq_usable =  1`) then this isn't a high priority. Just need to confirm that first.

**Comment by ericfeczko** [comment]
@perronea! I completely agree. If confirmed we should adjust this to a low priority.

**Comment by ericearl** [comment]
@perronea and @ericfeczko I confirmed what Anders suspected: there don't appear to be any rows where "Replaced" is followed by an "ftq_usable" of "1".

This accidental discovery may be a result of our current usage of the code: downloading absolutely everything and converting it to subset afterward.  This means we at NIMH DSST have to avoid the Replaced lines ourselves, but the typical usage of the code would not need to do this.

And @ericfeczko, we at the NIMH DSST already explored this topic with the NDA who said:

> The purpose of the Fast-QC table is to flag records from the Fast-Track series that are not 'recommended' due to QA issues. There are records in that table that were used to identify QA issues for older batches of fast-track data. The old data corresponds to the records with numerically smaller dataset-ids and submission-ids.
> 
> NDA uses this Fast-QC table to determine which records to package when a user requests the 'Recommended' series of Fast-Track data. The old data in this table has no effect on the packaging logic, but the old data in this table should not be used for analysis. I will bring this up with NDA staff since it makes sense to make this old data inaccessible to users.
