### ISSUE TITLE
Removing RawStorage

### ISSUE THREAD

**Issue by mriedel56** [DCAN-Labs/abcd-dicom2bids#42]
Just a couple small notes:
1) [this](https://github.com/DCAN-Labs/abcd-dicom2bids/blob/8f39c06515dbc65309fd70b4ff9e35585f1576ac/src/remove_RawDataStorage_dcms.py#L41) seems hard coded for a specific task (i.e., isn't 383 the number of TRs for one of the tasks)
2) Sometimes we found that one of those DICOMs did not exist, so we were left with a number of DICOMs not divisible by 60, which would cause dcm2niix to fail.

**Comment by arueter1** [comment]
Hi @mriedel56 - apologies for the extraordinarily long delay - we have been working on HBCD coding development this since you posted this. I am taking a few folks who may be able to help out in the next month or so. Feel free to close this issue if it's no longer relevant!
