### ISSUE TITLE
Only operates on text EventRelatedInformation

### ISSUE THREAD

**Issue by mriedel56** [DCAN-Labs/abcd-dicom2bids#43]
I think [this](https://github.com/DCAN-Labs/abcd-dicom2bids/blob/0b9495fe80b078548f3911435d050c7ade2b2349/src/unpack_and_setup.sh#L179) only operates on .txt files, but some event related information comes as a .csv file.

**Comment by rosemccollum** [comment]
This has been fixed with [PR #84](https://github.com/DCAN-Labs/abcd-dicom2bids/pull/84)
