### ISSUE TITLE
dcm2bids is incorrectly labeling some SEFMs from GE scanners

### ISSUE THREAD

**Issue by perronea** [DCAN-Labs/abcd-dicom2bids#46]
For the majority of SEFMs from GE scanners, the positive and negative (PA/AP) field maps are concatenated into a single file. The config file for dcm2bids (abcd_dcm2bids.conf L332) labels these field maps with "dir-both" if the SeriesDescription is ABCD-fMRI-FM* or ABCD-fMRI-FM_GE_original*. However, it looks like there are cases where the field maps from GE are already split prior to dcm to nifti conversion. In these cases there is an additional field in the metadata that can be used to identify the correct direction.

"PhaseEncodingPolarityGE": "Flipped" -->      dir-AP
"PhaseEncodingPolarityGE": "Unflipped" -->  dir-PA

I recommend adding the following to abcd_dcm2bids.conf:

        {
            "dataType": "fmap",
            "modalityLabel": "epi",
            "customLabels": "acq-func_dir-AP",
            "criteria": {
                "SeriesDescription": "ABCD-fMRI-FM_GE_original_*",
                "PhaseEncodingPolarityGE": "Flipped"
            }
        },
        {
            "dataType": "fmap",
            "modalityLabel": "epi",
            "customLabels": "acq-func_dir-AP",
            "criteria": {
                "SeriesDescription": "ABCD-fMRI-FM,*",
                "PhaseEncodingPolarityGE": "Flipped"
            }
        },
        {
            "dataType": "fmap",
            "modalityLabel": "epi",
            "customLabels": "acq-func_dir-PA",
            "criteria": {
                "SeriesDescription": "ABCD-fMRI-FM_GE_original_*",
                "PhaseEncodingPolarityGE": "Unflipped"
            }
        },
        {
            "dataType": "fmap",
            "modalityLabel": "epi",
            "customLabels": "acq-func_dir-PA",
            "criteria": {
                "SeriesDescription": "ABCD-fMRI-FM,*",
                "PhaseEncodingPolarityGE": "Unflipped"
            }
        },

**Comment by perronea** [comment]
Subjects with this issue will likely have the following (soft) error:

Traceback (most recent call last):
  File "/home/rando149/shared/code/internal/utilities/abcd-dicom2bids/src/sefm_eval_and_json_editor.py", line 430, in <module>
    sys.exit(main())
  File "/home/rando149/shared/code/internal/utilities/abcd-dicom2bids/src/sefm_eval_and_json_editor.py", line 362, in main
    seperate_concatenated_fm(layout, subject, sessions, fsl_dir)
  File "/home/rando149/shared/code/internal/utilities/abcd-dicom2bids/src/sefm_eval_and_json_editor.py", line 186, in seperate_concatenated_fm
    os.rename(os.path.join(FM_dir, "vol0001.nii.gz"), PA_fn)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/dicom2bids/NDARINVXXX/work/67d0a6f45dc2fe7b/BIDS_unprocessed/sub-NDARINVXXX/ses-baselineYear1Arm1/fmap/vol0001.nii.gz' -> '/tmp/dicom2bids/NDARINVXXX/work/67d0a6f45dc2fe7b/BIDS_unprocessed/sub-NDARINVXXX/ses-baselineYear1Arm1/fmap/sub-NDARINVXXX_ses-baselineYear1Arm1_acq-func_dir-PA_run-01_epi.nii.gz'

**Comment by begim-f** [comment]
This issue was solved by modifying and adding the new GE scanner to the config file for abcd-dicom2bids.
