### ISSUE TITLE
Running abcd2bids.py ends with a FileNotFoundError, however it doesnt affect the overall outputs

### ISSUE THREAD

**Issue by lundq163** [DCAN-Labs/abcd-dicom2bids#50]
When I run abcd2bids.py on a test subject, my terminal output will always finish with:
```
Traceback (most recent call last):
  File "/home/rando149/shared/code/internal/utilities/abcd-dicom2bids_nda/abcd2bids.py", line 761, in <module>
    main()
  File "/home/rando149/shared/code/internal/utilities/abcd-dicom2bids_nda/abcd2bids.py", line 89, in main
    globals()[step](cli_args)
  File "/home/rando149/shared/code/internal/utilities/abcd-dicom2bids_nda/abcd2bids.py", line 756, in validate_bids
    "/data"))
  File "/home/faird/shared/code/external/envs/miniconda3/mini3/lib/python3.7/subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/faird/shared/code/external/envs/miniconda3/mini3/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/faird/shared/code/external/envs/miniconda3/mini3/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/faird/shared/code/external/envs/miniconda3/mini3/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker': 'docker'
```
However, this does not seem to affect my overall outputs at all, as the `data` subdirectory is organized as expected in the ReadMe

**Comment by hough129** [comment]
@perronea I think this might be why those empty files exist in year 2. I haven't had time to diagnose, but I don't remember including singularity paths in my executable, and docker is not able to be used on MSI.

**Comment by perronea** [comment]
@lundq163 stated that it doesn't affect the outputs so I'm not sure about that, but the bids-validator step could definitely use some attention. It doesn't have to be a docker/singularity image, we can use the python package instead: https://pypi.org/project/bids-validator/

**Comment by hough129** [comment]
@lundq163 was meaning his outputs match mine, which would have the same exact errors because we ran the exact same commands (if there were any). And we didn't run a subject with 0-byte data (to my knowledge), so we wouldn't see those issues even if they would happen under these circumstances. Anyway, I'll test it out and report back when I can.

**Comment by lundq163** [comment]
@perronea Looks like I got a similar error with the BIDS validator step:
```
FATAL:   could not open image /usr/bin/singularity: image format not recognized
Error: BIDS validation failed.
```
This could be due to an error in my original run command when specifying the path to the executable. Here is my original run command:
```
python3 /home/rando149/shared/code/internal/utilities/abcd-dicom2bids_nda/abcd2bids.py /panfs/roc/msisoft/fsl/6.0.4/ /home/faird/shared/code/external/utilities/MATLAB_Runtime_R2021a/v910/ -q /home/faird/lundq163/NDA/nda-tools/downloadcmd/packages/1207913/abcd_fastqc01.txt -l /home/rando149/shared/projects/abcd2bids_test/subject_list_test -o /home/rando149/shared/projects/abcd2bids_test/jacob_output/ -p 1207151 --downloadcmd /home/faird/shared/code/external/envs/miniconda3/mini3/envs/abcd-dicom2bids/bin/downloadcmd --singularity /usr/bin/singularity 
```

**Comment by hough129** [comment]
@lundq163 I am pretty sure we figured this out within the team eventually. I am going to close this. Let me know if I am mistaken!
