### ISSUE TITLE
DWI grads for Philips version 5.6.1

### ISSUE THREAD

**Issue by gsudre** [DCAN-Labs/abcd-dicom2bids#57]
Hi,

Does anyone know if we can use the DWI Diffusion tables from Philip Achieva dStream 5.4 in [5.6.1", "5.6.1.1"] scans? There are a few of those in the fast track data for FU2, but I don't see specific tables for that version.

Thanks!

G

**Comment by audreymhoughton** [comment]
This was fixed in #74 and #76 .
