### ISSUE TITLE
abcd-dicom2bids fails with scans in tabular release

### ISSUE THREAD

**Issue by gsudre** [DCAN-Labs/abcd-dicom2bids#58]
Hello,

I was wondering if you could help shed some light on these weird cases. I've been trying to process the ABCD DWI data for several subjects that pass DWI QC according to the tabular data, but when using the abcd-dcm2bids tools and the downloaded fast-track raw data they crash. Specifically, they crash during dcm2nii, and the error indicates that the sequence is not complete.

Have you run into any issues like that? Or maybe the pipeline used to produce the tabular data ignores incomplete volumes? I'm happy to provide more details or a few examples.

Thanks!

**Comment by hough129** [comment]
@gsudre abcd-dicom2bids fails due to incomplete volumes, yes. I believe this is a characteristic of dcm2nii, not something we've done within abcd-dicom2bids itself. @madisoth might have more insight.

**Comment by ericearl** [comment]
This issue also relates to #47.
