### ISSUE TITLE
Clarify Directions for Usage

### ISSUE THREAD

**Issue by MIZwally** [DCAN-Labs/abcd-dicom2bids#66]
### A short summary of what you would like to see in abcd-dicom2bids.

It would be helpful to add the flags needed for each of the respective fields in the code line outlining what is needed to run abcd-dicom2bids.py. For example adding the -q flag for the fast-qc location, -l for subject list, and -p for package name. I could not run the code without these flags.

### Do you have any interest in helping implement the feature?

No :(

**Comment by rosemccollum** [comment]
Documentation has been updated!
