### ISSUE TITLE
Question about run_eta_squared.sh

### ISSUE THREAD

**Issue by tientong98** [DCAN-Labs/abcd-dicom2bids#7]
Hi,

When running the `run_eta_squared.sh` script, I encountered an error of not being able to create the $TMPDIR/$USER 

https://github.com/DCAN-Labs/abcd-dicom2bids/blob/8169f7809d8f356ab86ae3b77d1500a807ea416e/src/run_eta_squared.sh#L10

This is because I don't have  the $TMPDIR variable on my PATH, i.e., when I do `echo "$TMPDIR"`, the output is blank. I don't think that $TMPDIR was assigned elsewhere; therefore, I was wondering if the script can be changed to `/tmp` instead of $TMPDIR. I have tried to assign the $TMPDIR variable to a random tmp directory, then do `mkdir -p $TMPDIR/$USER `, and was able to run through the script without error.

**Comment by GregConan** [comment]
Fixed in [commit on 2020-01-31](https://github.com/DCAN-Labs/abcd-dicom2bids/commit/be5782050dae7464e937b00287638c4ff4adf2f7): Bash scripts now automatically set the `$TMPDIR` variable if it is not already set
