### ISSUE TITLE
ERROR setting up DWI: (Philips and GE) software version not recognized

### ISSUE THREAD

**Issue by ericearl** [DCAN-Labs/abcd-dicom2bids#71]
### What happened?

Doing conversions in batches of 2 subjects, the following errors stop the conversion from succeeding in newer scans where the scanner software versions are newer than 5.4 for Philips and newer than DV26 for GE.

The errors and counts of their appearances among all the logs from ABCD fast track data as of late October 2023 are...

88 times:
> ERROR setting up DWI: Philips software version  [5.6.1\5.6.1.1]  not recognized

69 times:
> ERROR setting up DWI: Philips software version  [5.6.1\5.6.1.2]  not recognized

9 times:
> ERROR setting up DWI: GE software version not recognized

1 time:
> ERROR setting up DWI: Philips software version  [5.7.1\5.7.1.0]  not recognized

These are always preceded by the line:

> Replacing bvals and bvecs with files supplied by the NDA

### What command did you use?

```shell
python3 \
    ${TEMP_PATH}/scripts/abcd-dicom2bids/abcd2bids.py \
    ${FSLDIR} \
    ${TEMP_PATH}/scripts/abcd-dicom2bids/env_setup/MCR_v9.1 \
    -l ${TEMP_PATH}/inputs/subjects.txt \
    -p ${ABCD_FASTTRACK_IMAGING_PACKAGE} \
    -s reformat_fastqc_spreadsheet \
    --downloadcmd ${TEMP_PATH}/scripts/abcd-dicom2bids/abcd_env/bin/downloadcmd \
    -x /data/MLDSST/containers/bids-validator-1.9.9.simg \
    -q ${TEMP_PATH}/scripts/abcd-dicom2bids/spreadsheets/abcd_fastqc01.txt"
```

### What version of abcd-dicom2bids are you using?

Our barely altered fork at https://github.com/nih-fmrif/abcd-dicom2bids

### Directory Structure

The conversion fails, so I don't get outputs back. Happy to add any other helping info you need though, let me know.

### Relevant log output

```shell
# happens in unpack_and_setup.sh

        if [[ `dcmdump --search 0008,0070 ${first_dcm} 2>/dev/null` == *GE* ]]; then 
            if dcmdump --search 0018,1020 ${first_dcm} 2>/dev/null | grep -q DV25; then
                echo "Replacing GE DV25 bvals and bvecs"
                echo cp `dirname $0`/ABCD_Release_2.0_Diffusion_Tables/GE_bvals_DV25.txt ${orig_bval}
                cp `dirname $0`/ABCD_Release_2.0_Diffusion_Tables/GE_bvals_DV25.txt ${orig_bval}
                echo cp `dirname $0`/ABCD_Release_2.0_Diffusion_Tables/GE_bvecs_DV25.txt ${orig_bvec}
                cp `dirname $0`/ABCD_Release_2.0_Diffusion_Tables/GE_bvecs_DV25.txt ${orig_bvec}
            elif dcmdump --search 0018,1020 ${first_dcm} 2>/dev/null | grep -q DV26; then
                echo "Replacing GE DV26 bvals and bvecs"
                cp `dirname $0`/ABCD_Release_2.0_Diffusion_Tables/GE_bvals_DV26.txt ${orig_bval}
                cp `dirname $0`/ABCD_Release_2.0_Diffusion_Tables/GE_bvecs_DV26.txt ${orig_bvec}
            else
                echo "ERROR setting up DWI: GE software version not recognized"
                exit
            fi
        elif [[ `dcmdump --search 0008,0070 ${first_dcm} 2>/dev/null` == *Philips* ]]; then
            software_version=`dcmdump --search 0018,1020 ${first_dcm} 2>/dev/null | awk '{print $3}'`
            if [[ ${software_version} == *5.3* ]]; then
                echo "Replacing Philips s1 bvals and bvecs"
                cp `dirname $0`/ABCD_Release_2.0_Diffusion_Tables/Philips_bvals_s1.txt ${orig_bval}
                cp `dirname $0`/ABCD_Release_2.0_Diffusion_Tables/Philips_bvecs_s1.txt ${orig_bvec}
            elif [[ ${software_version} == *5.4* ]]; then
                echo "Replacing Philips s2 bvals and bvecs"
                cp `dirname $0`/ABCD_Release_2.0_Diffusion_Tables/Philips_bvals_s2.txt ${orig_bval}
                cp `dirname $0`/ABCD_Release_2.0_Diffusion_Tables/Philips_bvecs_s2.txt ${orig_bvec}
            else
                echo "ERROR setting up DWI: Philips software version " ${software_version} " not recognized"
                exit
            fi
```

### Add any additional information or context about the problem here.

A check on the ABCD_Diffusion_Tables.zip on NDA collection 2573 revealed the current files there are the same as there are already in this repo from ABCD release 2.0. So the solution will be getting the latest diffusion tables, uploading them into this repo, adding a new case for each relevant diffusion table file in `unpack_and_setup.sh`, and releasing a new version.

I have an email out to Elizabeth Hoffman asking who might have this info, but she has not responded yet.

**Comment by ericearl** [comment]
Oh, and #57 is related!

**Comment by rosemccollum** [comment]
@ericearl was this issue fixed in [this PR](https://github.com/DCAN-Labs/abcd-dicom2bids/pull/76) or is this still an issue?

**Comment by ericearl** [comment]
#76 did away with the errors that would arise in this issue, but I haven't tested it yet. I won't be testing it for a few weeks still.

**Comment by audreymhoughton** [comment]
We tested it. Closing this issue. Thanks!
