### ISSUE TITLE
run_order_fix.py is hard-coded to ses-baselineYear1Arm1

### ISSUE THREAD

**Issue by ericearl** [DCAN-Labs/abcd-dicom2bids#80]
### What happened?

It looks like maybe ALL the data that isn't `ses-baselineYear1Arm1` could be incorrectly ordered fMRI runs due to the hard-coded `ses-baselineYear1Arm1` and the reliance on `run_order_fix.py` in `unpack_and_setup.sh`:

- https://github.com/DCAN-Labs/abcd-dicom2bids/blob/main/src/run_order_fix.py#L163-L164
- https://github.com/DCAN-Labs/abcd-dicom2bids/blob/main/src/unpack_and_setup.sh#L132-L145

### What command did you use?

```shell
python run_order_fix.py --get-bids-errors --generate-map outputs/round_13/sub-NDARANONYMIZED outputs/round_13_sub-NDARANONYMIZED_error.json outputs/round_13_sub-NDARANONYMIZED_file_map.json --subject sub-NDARANONYMIZED
```

### What version of abcd-dicom2bids are you using?

Our barely altered fork at [https://github.com/nih-fmrif/abcd-dicom2bids](https://github.com/nih-fmrif/abcd-dicom2bids).

### Directory Structure

```
outputs/round_13/sub-NDARANONYMIZED
├── ses-2YearFollowUpYArm1
│   ├── anat
│   ├── dwi
│   ├── fmap
│   └── func
├── ses-4YearFollowUpYArm1
│   ├── anat
│   ├── dwi
│   ├── fmap
│   └── func
└── ses-baselineYear1Arm1
    ├── anat
    ├── dwi
    ├── fmap
    └── func
```

### Relevant log output

```shell
> python run_order_fix.py --get-bids-errors --generate-map outputs/round_13/sub-NDARANONYMIZED outputs/round_13_sub-NDARANONYMIZED_error.json outputs/round_13_sub-NDARANONYMIZED_file_map.json --subject sub-NDARANONYMIZED
sub-NDARANONYMIZED
sub-NDARANONYMIZED
sub-NDARANONYMIZED
sub-NDARANONYMIZED
> head outputs/round_13_sub-NDARANONYMIZED_*.json
==> outputs/round_13_sub-NDARANONYMIZED_error.json <==
{"sub-NDARANONYMIZED": {"rest": {"current_order": [1, 2, 3, 4], "actual_order": [1, 4, 2, 3]}}}
==> outputs/round_13_sub-NDARANONYMIZED_file_map.json <==
{}
```

### Add any additional information or context about the problem here.

I think `run_order_fix.py` is supposed to only print the BIDS participant ID once when it runs successfully. I am still trying to debug why it might be printing 4 times in my testing...

**Comment by LuciMoore** [comment]
we are developing a new version of this code to work with data provided via s3 buckets in place of the NDA. the aws_donwloader has been modified to download from the s3 bukcket and to account for the chnages in the organization of files in the s3 bucket. For example early on all dicoms were in a zipped folder. However, now it is modality wise. So the data is organised as sub_id/ses_id/func/{zipped_file_for_each_run}. 
Note- This zipped file only has the dicoms, not the jsons.
